# Generated by Django 3.2.8 on 2021-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='avg_price_per_hour',
            field=models.FloatField(help_text='Average price per hour', null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='description',
            field=models.TextField(help_text='Few words of the Performer about himself/herself', null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='latitude',
            field=models.FloatField(help_text="Performer's last order latitude", null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='longitude',
            field=models.FloatField(help_text="Performer's last order longitude", null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='work_day_end',
            field=models.TimeField(help_text="Performer's work day end", null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='work_day_start',
            field=models.TimeField(help_text="Performer's work day start", null=True),
        ),
    ]
