# Generated by Django 3.2.8 on 2021-11-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(help_text='Image for the avatar', null=True, upload_to='media/avatars'),
        ),
    ]
