# Generated by Django 3.2.8 on 2021-11-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211111_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='performer_specialization_id',
            field=models.ForeignKey(help_text="ID of the Performer's  specialization from the PerformerSpecialization table", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.performerspecialization'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='status_is',
            field=models.ForeignKey(help_text="ID of the Performer's current status from the PerformerStatus table", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.performerstatus'),
        ),
    ]
