version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@kpi.ua
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
  app:
    build: .
    env_file:
      - .env
    command: sh -c "python3 main.py"
    container_name: python_app
    depends_on:
      - db
    image: app-image
volumes:
  postgres:
  pgadmin: