# Generated by Django 3.2.8 on 2021-11-12 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, help_text='Requester complaint text', null=True)),
                ('admin_comment', models.TextField(blank=True, help_text='Admin comment', null=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the complaint creating')),
                ('resolve_date', models.DateTimeField(blank=True, help_text='Date and time of the complaint resolving', null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('admin_id', models.ForeignKey(help_text='ID of the Admin that assigned to the complaint', on_delete=django.db.models.deletion.DO_NOTHING, to='users.admin')),
                ('requester_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('order_status_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('CRTD', 'Created'), ('ACCPTD', 'Accepted'), ('INPRGRS', 'In progress'), ('ADMN', 'Complaint under consideration by the administrator')], help_text='Order status', max_length=16)),
            ],
            options={
                'verbose_name': 'Order status',
                'verbose_name_plural': 'Order statuses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, help_text='Order address', null=True)),
                ('latitude', models.FloatField(help_text='Order address latitude')),
                ('longitude', models.FloatField(help_text='Order address longitude')),
                ('comment', models.TextField(blank=True, help_text='Order additional comment', null=True)),
                ('is_high_priority', models.BooleanField(default=False, help_text='True if order is urgent')),
                ('date', models.DateTimeField(auto_now=True, help_text='Date and time of the order creation')),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date and time of the order completion', null=True)),
                ('customer_approved', models.BooleanField(default=False, help_text='True if customer approved the work')),
                ('performer_approved', models.BooleanField(default=False, help_text='True if performer approved the work')),
                ('complaint_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.complaint')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.customer')),
                ('order_status_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.orderstatus')),
                ('performer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.performer')),
            ],
        ),
    ]
