# Generated by Django 3.2.8 on 2021-11-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of the complaint creating'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolve_date',
            field=models.DateTimeField(help_text='Date and time of the complaint resolving', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of the order creation'),
        ),
    ]
